### ISSUE TITLE
Incorrect Exit Coordinate

### ISSUE THREAD

**Issue by alexkoisine** [Jonirulah/esx_housing#4]
exit coords incorrect, when i have more than 1 property and invite others player to join property and the guest exit property with the wrong coordinate, the guest teleport not to current property but teleport to visited property before

Thanks

**Comment by Jonirulah** [comment]
Should be fixed now, you can always turn debug printing, so in the client and server side debugging is active and I can see exactly what's going on, I figured out where the error should be but in case it doesn't get fixed just tell me!

**Comment by gerung** [comment]
hmm, the issue now when the owned property exit property, the owned can't entering house
Thanks
