### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by alexkoisine** [Jonirulah/esx_housing#9]
It's possible to add house gateway, i mean like aparment so when buying a room, you can go through the menu which contains a list of available rooms, thanks

**Comment by Jonirulah** [comment]
definetily this is an option, however the script wasn't intended to fill for that purpose, so yeah, this is an option, so yeah, if someone wants to do their enhanced version, they can always fork the github project or make a PR

But answering your question, I don't intend on doing this at this moment.
